version: "3"

services:
  # Название сервиса
  mongo:
    # Образ с hub.docker.com
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
    # Проброс файлов родитель:контейнер. MongoDB будет создавать свои файлы
    volumes:
      - ./mongo:/data/db
    # Проброс порта родитель:контейнер
    ports:
      - "27017:27017"
    # Использование сети
    networks:
      # Название сети
      - app

  # Название сервиса
  server-app:
    # Сборка про Dockerfile находящемуся в корне
    build:
      context: .
    # Переменные окружения
    environment:
      # Хост mongo с портом 27017 будет создан в сервисе mongo
      - MONGO_HOST=mongo
    # Секретные переменные окружения
    env_file:
      ./.env
    # Проброс порта родитель:контейнер
    ports:
      - "4000:3000"
    # Проброс файлов родитель:контейнер
    volumes:
      - ./shared:/app/shared
    # Зависимость от mongo
    depends_on:
      - mongo
    # Использование сети
    networks:
      # Название сети
      - app
    # Дожидаться запуска MongoDB
    command: ./wait-for.sh mongo:27017 -- npm start

# Связать созданные сервисы по сети
networks:
  # Название сети
  app:
    driver: bridge
